config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  #New User
  get  'register'     => 'users#new', as: 'new_register'
  get  'users/new'    => 'users#new'

  #Create User
  post 'register'     => 'users#create', as: 'register'
  post 'users'        => 'users#create'

  #Show User
  get  'users/:id'    => 'users#show',   as: 'user'

  #New Login
  get  'login'        => 'sessions#new', as: 'new_login'
  get  'sessions/new' => 'sessions#new'

  #Login
  post 'login'        => 'sessions#create', as: 'login'
  post 'sessions'     => 'sessions#create'

  #Logout
  delete 'logout'     => 'sessions#destroy', as: 'logout'
  delete 'sessions'   => 'sessions#destroy'

  resources :secrets, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]
#   get 'secrets/index'
#
# resources :sessions, only: [:new, :create, :destroy]
# resources :users
# resources :secrets, only: [:index, :create, :destroy]
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :secret
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :secrets
  has_many :likes, dependent: :destroy
  has_many :secrets_liked, through: :likes, source: :secret
  has_secure_password

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

    validates :first_name, :last_name,  presence: true
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	  User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    Like.create like_params
    redirect_to "/secrets"
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy if current_user === @like.user
    redirect_to "/secrets"
  end

  private
    def like_params
      params.require(:like).permit(:secret_id).merge(user: current_user)
    end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def index
    @secrets = Secret.all
  end

  def create
    secret = Secret.new secret_params
    unless secret.save
      flash[:errors] = secret.errors.full_messages
    end
    redirect_to "/users/#{current_user.id}"
  end

  def destroy
    @secret = Secret.find(params[:id])
    @secret.destroy if @secret.user === current_user
    redirect_to "/users/#{current_user.id}"
  end

  private
    def secret_params
      params.require(:secret).permit(:content).merge(user: current_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create 
		user = User.find_by_email(params[:user][:email])

		if user
			if user.try(:authenticate, params[:user][:password])
				session[:user_id] = user.id

				return redirect_to user_path user.id

			end

			flash[:errors] = ['password is not correct.']
		else
			flash[:errors] = ['Account not found, please register first.']
		end

		return redirect_to :back

	end

	def destroy
		session.delete(:user_id) if session[:user_id]

		return redirect_to new_login_path
	end
end

app/controllers/users_controller.rb
# class UsersController < ApplicationController
# 	def new
#
# 	end
#
# 	def create
# 		user = User.create(user_params)
#
# 		if user.valid?
# 			session[:user_id] = user.id
#
# 			return redirect_to user_path user.id
# 		end
#
#            flash[:errors] = user.errors.full_messages
#
# 		return redirect_to :back
# 	end
#
# 	def show
# 		@user = User.find(params[:id])
# 	end
#
# 	def destroy
#
# 	end
#
# 	private
# 		def user_params
# 			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_comfirmation)
# 		end
# end


class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])

  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to "/sessions/new"
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to "/users/new"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update user_params
      redirect_to "/users/#{@user.id}"
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to "/users/#{@user.id}/edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      reset_session
      redirect_to "/users/new"
    else
      redirect_to "/users/#{@user.id}/edit"
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dojosecrets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>



</head>
<body>
<div class="container-fluid">

<ul class="nav justify-content-end">
	<% if current_user %>
  <li class="nav-item">
    <a class="nav-link active" href="<%= logout_path %>" data-method= "delete" >Logout</a>
  </li>
  <% else %>
  <li class="nav-item">
    <a class="nav-link" href="<%= new_register_path %>">Register</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= new_login_path %>">Login</a>
  </li>
  <% end %>
</ul>

	<!-- Errors -->
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %> 
			<p class="text-danger"><%= error %></p>
			<% end %>
	 <% end %>
	<%= yield %>
</div>


</body>
</html>

app/views/secrets/index.html.erb
<h1>All Secrets</h1>
<% @secrets.all.each do |secret| %>
	<h1><%= secret.content %></h1>
	<h3><%= secret.likes.count %> likes</h3>
	<% if secret.user == current_user %>
		<form action = "/secrets/<%= secret.id %>" method = "post">
		    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="delete">
			<input type = 'submit' value = "Delete Secret">
		</form>
	<% end %>
	<% unless secret.users.include?(current_user) %>
		<form action = "/likes" method = "post">
		    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		    <input type="hidden" name="like[secret_id]" value = "<%= secret.id %>">
			<input type="submit" name="Like" value = "Like">
		</form>
	<% else %>
		<form action = "/likes/<%= Like.where(user: current_user, secret: secret).first.id%>" method = "post">
		    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="delete">
			<input type="submit" name="Unlike" value = "Unlike">
		</form>
	<% end %>
<% end %>

app/views/users/new.html.erb
  <body class="body-green" data-elink-extension-installed="1.1.5">

    <!-- Body -->
	<div class="wrapper body-inverse"> <!-- wrapper -->
	  <div class="container">
	    <div class="row">
		  <!-- Sign In form -->
		  <!-- <div class="col-sm-5 col-sm-offset-1">
		    <h3>Sign In to your account</h3>
			<p class="text-muted">
			  Please fill out the form below to login to your account.
			</p>
			<div class="form-white">
			  <form role="form">
			    <div class="form-group">
				  <label for="email">Email address</label>
				  <input type="email" class="form-control" id="email" placeholder="Enter email">
			    </div>
			    <div class="form-group">
				  <label for="password">Password</label>
				  <input type="password" class="form-control" id="password" placeholder="Password">
			    </div>
			    
			    <button type="submit" class="btn btn-block btn-color btn-xxl">Submit</button>
			  </form>
			  <hr>
			  
			  <div class="hidden" id="lost-form">
			  
				
			  </div>
			  <div class="form-avatar hidden-xs">
				<span class="fa-stack fa-4x">
				  <i class="fa fa-circle fa-stack-2x"></i>
				  <i class="fa fa-user fa-stack-1x"></i>
				</span>
			  </div>
			</div>
		  </div> -->
		  <!-- Sign Up form -->
		  <div class="col-sm-5">
		    <h3 class="text-right-xs">Registration</h3>
			<p class="text-muted text-right-xs">
			  Please fill out the form below to create a new account.
			</p>
			<div class="form-white">
				<form action="<%= register_path %>" method="post" class="form">
					<input type = "hidden" name = "authenticity_token" value = "<%=form_authenticity_token %>" >

				  <div class="form-group">
				    <label for="name">First Name</label>
					<input type="text" name="user[first_name]" class="form-control" id="first_name" placeholder="First Name">
				  </div>
				  <div class="form-group">
				    <label for="username">Last Name</label>
					<input type="text" name="user[last_name]" class="form-control" id="last_name" placeholder="Last Name">
				  </div>
				  <div class="form-group">
				    <label for="email2">Email address</label>
					<input type="email" name="user[email]" class="form-control" id="email" placeholder="Enter email">
				  </div>
				  <div class="form-group">
					<div class="row">
					  <div class="col-sm-6">
					  <label for="password2">Password</label>
					  <input type="password" name="user[password]" class="form-control" id="password" placeholder="Password">
					  </div>
					  <div class="col-sm-6">
					  <label for="password2">Confirm password</label>
					  <input type="password" name="user[password_confirmation]" class="form-control" id="password" placeholder="Password Confirmation">
					  </div>
					</div>
				  </div>
				  
				  <button type="submit" class="btn btn-block btn-color btn-xxl">Create an account</button>
				</form>
			</div>
		  </div>
		</div>
	  </div>
	</div> <!-- / wrapper -->
    

app/views/users/show.html.erb
<!--



<h1>Show Page</h1>

<p>First Name:<%= @user.first_name %></p> -->


<h1><%= @user.first_name %></h1>

<form action = "/secrets" method = "post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="text" id="Content" name = "secret[content]">
	<input type="submit" value = "Create Secret">
</form>

<% @user.secrets.each do |secret| %>
	<h1><%= secret.content %></h1>
	<h3><%= secret.likes.count %> likes</h3>
	<% if secret.user == current_user %>
		<form action = "/secrets/<%= secret.id %>" method = "post">
		    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="delete">
			<input type = 'submit' value = 'Delete Secret'>
		</form>
	<% end %>
<% end %>